zuul:
  routes:
    catalog:
      url: /catalog/**
      service-id: catalog-service
    order:
      url: /order/**
      service-id: order-service

server:
  port: 8765

spring:
  application:
    name: gateway-service

#Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000